version: '3.8'
services:
    runner:
        image: myoung34/github-runner:latest
        container_name: github-runner
        environment:
            REPO_URL: https://github.com/naelpardd09/tugas-10-juli-docker
            RUNNER_NAME: laptop-runner
            RUNNER_TOKEN: BEKMXUV3EDHE6ZKQ43IRMVLKKRF5G   # ganti dengan token
            LABELS: docker-local-cicd
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./runner-data:/runner/data
        restart: unless-stopped

